# Generated by Django 3.0.7 on 2020-07-03 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=120)),
                ('password', models.CharField(max_length=120)),
                ('firstname', models.CharField(max_length=120)),
                ('lastname', models.CharField(max_length=120)),
                ('role', models.CharField(max_length=120)),
                ('email', models.CharField(max_length=120)),
                ('countrycode', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=120)),
            ],
        ),
    ]
