# Generated by Django 3.0.7 on 2020-07-10 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0004_auto_20200710_0934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='id',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user',
            field=models.CharField(max_length=120, primary_key=True, serialize=False),
        ),
    ]
